// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lb_listener.proto

package terraform_aws

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type LbListener struct {
	Arn             string                      `protobuf:"bytes,1,opt,name=arn,proto3" json:"arn,omitempty"`
	CertificateArn  string                      `protobuf:"bytes,2,opt,name=certificate_arn,json=certificateArn,proto3" json:"certificate_arn,omitempty"`
	DefaultAction   []*LbListener_DefaultAction `protobuf:"bytes,3,rep,name=default_action,json=defaultAction,proto3" json:"default_action,omitempty"`
	LoadBalancerArn string                      `protobuf:"bytes,4,opt,name=load_balancer_arn,json=loadBalancerArn,proto3" json:"load_balancer_arn,omitempty"`
	Port            int64                       `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	Protocol        string                      `protobuf:"bytes,6,opt,name=protocol,proto3" json:"protocol,omitempty"`
	SslPolicy       string                      `protobuf:"bytes,7,opt,name=ssl_policy,json=sslPolicy,proto3" json:"ssl_policy,omitempty"`
}

func (m *LbListener) Reset()         { *m = LbListener{} }
func (m *LbListener) String() string { return proto.CompactTextString(m) }
func (*LbListener) ProtoMessage()    {}
func (*LbListener) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d2373b4195c780, []int{0}
}
func (m *LbListener) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LbListener) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LbListener.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LbListener) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LbListener.Merge(m, src)
}
func (m *LbListener) XXX_Size() int {
	return m.Size()
}
func (m *LbListener) XXX_DiscardUnknown() {
	xxx_messageInfo_LbListener.DiscardUnknown(m)
}

var xxx_messageInfo_LbListener proto.InternalMessageInfo

func (m *LbListener) GetArn() string {
	if m != nil {
		return m.Arn
	}
	return ""
}

func (m *LbListener) GetCertificateArn() string {
	if m != nil {
		return m.CertificateArn
	}
	return ""
}

func (m *LbListener) GetDefaultAction() []*LbListener_DefaultAction {
	if m != nil {
		return m.DefaultAction
	}
	return nil
}

func (m *LbListener) GetLoadBalancerArn() string {
	if m != nil {
		return m.LoadBalancerArn
	}
	return ""
}

func (m *LbListener) GetPort() int64 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *LbListener) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *LbListener) GetSslPolicy() string {
	if m != nil {
		return m.SslPolicy
	}
	return ""
}

type LbListener_DefaultAction struct {
	AuthenticateCognito []*LbListener_DefaultAction_AuthenticateCognito `protobuf:"bytes,1,rep,name=authenticate_cognito,json=authenticateCognito,proto3" json:"authenticate_cognito,omitempty"`
	AuthenticateOidc    []*LbListener_DefaultAction_AuthenticateOidc    `protobuf:"bytes,2,rep,name=authenticate_oidc,json=authenticateOidc,proto3" json:"authenticate_oidc,omitempty"`
	FixedResponse       []*LbListener_DefaultAction_FixedResponse       `protobuf:"bytes,3,rep,name=fixed_response,json=fixedResponse,proto3" json:"fixed_response,omitempty"`
	Order               int64                                           `protobuf:"varint,4,opt,name=order,proto3" json:"order,omitempty"`
	Redirect            []*LbListener_DefaultAction_Redirect            `protobuf:"bytes,5,rep,name=redirect,proto3" json:"redirect,omitempty"`
	TargetGroupArn      string                                          `protobuf:"bytes,6,opt,name=target_group_arn,json=targetGroupArn,proto3" json:"target_group_arn,omitempty"`
	Type                string                                          `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
}

func (m *LbListener_DefaultAction) Reset()         { *m = LbListener_DefaultAction{} }
func (m *LbListener_DefaultAction) String() string { return proto.CompactTextString(m) }
func (*LbListener_DefaultAction) ProtoMessage()    {}
func (*LbListener_DefaultAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d2373b4195c780, []int{0, 0}
}
func (m *LbListener_DefaultAction) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LbListener_DefaultAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LbListener_DefaultAction.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LbListener_DefaultAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LbListener_DefaultAction.Merge(m, src)
}
func (m *LbListener_DefaultAction) XXX_Size() int {
	return m.Size()
}
func (m *LbListener_DefaultAction) XXX_DiscardUnknown() {
	xxx_messageInfo_LbListener_DefaultAction.DiscardUnknown(m)
}

var xxx_messageInfo_LbListener_DefaultAction proto.InternalMessageInfo

func (m *LbListener_DefaultAction) GetAuthenticateCognito() []*LbListener_DefaultAction_AuthenticateCognito {
	if m != nil {
		return m.AuthenticateCognito
	}
	return nil
}

func (m *LbListener_DefaultAction) GetAuthenticateOidc() []*LbListener_DefaultAction_AuthenticateOidc {
	if m != nil {
		return m.AuthenticateOidc
	}
	return nil
}

func (m *LbListener_DefaultAction) GetFixedResponse() []*LbListener_DefaultAction_FixedResponse {
	if m != nil {
		return m.FixedResponse
	}
	return nil
}

func (m *LbListener_DefaultAction) GetOrder() int64 {
	if m != nil {
		return m.Order
	}
	return 0
}

func (m *LbListener_DefaultAction) GetRedirect() []*LbListener_DefaultAction_Redirect {
	if m != nil {
		return m.Redirect
	}
	return nil
}

func (m *LbListener_DefaultAction) GetTargetGroupArn() string {
	if m != nil {
		return m.TargetGroupArn
	}
	return ""
}

func (m *LbListener_DefaultAction) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type LbListener_DefaultAction_AuthenticateCognito struct {
	AuthenticationRequestExtraParams map[string]string `protobuf:"bytes,1,rep,name=authentication_request_extra_params,json=authenticationRequestExtraParams,proto3" json:"authentication_request_extra_params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	OnUnauthenticatedRequest         string            `protobuf:"bytes,2,opt,name=on_unauthenticated_request,json=onUnauthenticatedRequest,proto3" json:"on_unauthenticated_request,omitempty"`
	Scope                            string            `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	SessionCookieName                string            `protobuf:"bytes,4,opt,name=session_cookie_name,json=sessionCookieName,proto3" json:"session_cookie_name,omitempty"`
	SessionTimeout                   int64             `protobuf:"varint,5,opt,name=session_timeout,json=sessionTimeout,proto3" json:"session_timeout,omitempty"`
	UserPoolArn                      string            `protobuf:"bytes,6,opt,name=user_pool_arn,json=userPoolArn,proto3" json:"user_pool_arn,omitempty"`
	UserPoolClientId                 string            `protobuf:"bytes,7,opt,name=user_pool_client_id,json=userPoolClientId,proto3" json:"user_pool_client_id,omitempty"`
	UserPoolDomain                   string            `protobuf:"bytes,8,opt,name=user_pool_domain,json=userPoolDomain,proto3" json:"user_pool_domain,omitempty"`
}

func (m *LbListener_DefaultAction_AuthenticateCognito) Reset() {
	*m = LbListener_DefaultAction_AuthenticateCognito{}
}
func (m *LbListener_DefaultAction_AuthenticateCognito) String() string {
	return proto.CompactTextString(m)
}
func (*LbListener_DefaultAction_AuthenticateCognito) ProtoMessage() {}
func (*LbListener_DefaultAction_AuthenticateCognito) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d2373b4195c780, []int{0, 0, 0}
}
func (m *LbListener_DefaultAction_AuthenticateCognito) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LbListener_DefaultAction_AuthenticateCognito) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LbListener_DefaultAction_AuthenticateCognito.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LbListener_DefaultAction_AuthenticateCognito) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LbListener_DefaultAction_AuthenticateCognito.Merge(m, src)
}
func (m *LbListener_DefaultAction_AuthenticateCognito) XXX_Size() int {
	return m.Size()
}
func (m *LbListener_DefaultAction_AuthenticateCognito) XXX_DiscardUnknown() {
	xxx_messageInfo_LbListener_DefaultAction_AuthenticateCognito.DiscardUnknown(m)
}

var xxx_messageInfo_LbListener_DefaultAction_AuthenticateCognito proto.InternalMessageInfo

func (m *LbListener_DefaultAction_AuthenticateCognito) GetAuthenticationRequestExtraParams() map[string]string {
	if m != nil {
		return m.AuthenticationRequestExtraParams
	}
	return nil
}

func (m *LbListener_DefaultAction_AuthenticateCognito) GetOnUnauthenticatedRequest() string {
	if m != nil {
		return m.OnUnauthenticatedRequest
	}
	return ""
}

func (m *LbListener_DefaultAction_AuthenticateCognito) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *LbListener_DefaultAction_AuthenticateCognito) GetSessionCookieName() string {
	if m != nil {
		return m.SessionCookieName
	}
	return ""
}

func (m *LbListener_DefaultAction_AuthenticateCognito) GetSessionTimeout() int64 {
	if m != nil {
		return m.SessionTimeout
	}
	return 0
}

func (m *LbListener_DefaultAction_AuthenticateCognito) GetUserPoolArn() string {
	if m != nil {
		return m.UserPoolArn
	}
	return ""
}

func (m *LbListener_DefaultAction_AuthenticateCognito) GetUserPoolClientId() string {
	if m != nil {
		return m.UserPoolClientId
	}
	return ""
}

func (m *LbListener_DefaultAction_AuthenticateCognito) GetUserPoolDomain() string {
	if m != nil {
		return m.UserPoolDomain
	}
	return ""
}

type LbListener_DefaultAction_AuthenticateOidc struct {
	AuthenticationRequestExtraParams map[string]string `protobuf:"bytes,1,rep,name=authentication_request_extra_params,json=authenticationRequestExtraParams,proto3" json:"authentication_request_extra_params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	AuthorizationEndpoint            string            `protobuf:"bytes,2,opt,name=authorization_endpoint,json=authorizationEndpoint,proto3" json:"authorization_endpoint,omitempty"`
	ClientId                         string            `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret                     string            `protobuf:"bytes,4,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	Issuer                           string            `protobuf:"bytes,5,opt,name=issuer,proto3" json:"issuer,omitempty"`
	OnUnauthenticatedRequest         string            `protobuf:"bytes,6,opt,name=on_unauthenticated_request,json=onUnauthenticatedRequest,proto3" json:"on_unauthenticated_request,omitempty"`
	Scope                            string            `protobuf:"bytes,7,opt,name=scope,proto3" json:"scope,omitempty"`
	SessionCookieName                string            `protobuf:"bytes,8,opt,name=session_cookie_name,json=sessionCookieName,proto3" json:"session_cookie_name,omitempty"`
	SessionTimeout                   int64             `protobuf:"varint,9,opt,name=session_timeout,json=sessionTimeout,proto3" json:"session_timeout,omitempty"`
	TokenEndpoint                    string            `protobuf:"bytes,10,opt,name=token_endpoint,json=tokenEndpoint,proto3" json:"token_endpoint,omitempty"`
	UserInfoEndpoint                 string            `protobuf:"bytes,11,opt,name=user_info_endpoint,json=userInfoEndpoint,proto3" json:"user_info_endpoint,omitempty"`
}

func (m *LbListener_DefaultAction_AuthenticateOidc) Reset() {
	*m = LbListener_DefaultAction_AuthenticateOidc{}
}
func (m *LbListener_DefaultAction_AuthenticateOidc) String() string { return proto.CompactTextString(m) }
func (*LbListener_DefaultAction_AuthenticateOidc) ProtoMessage()    {}
func (*LbListener_DefaultAction_AuthenticateOidc) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d2373b4195c780, []int{0, 0, 1}
}
func (m *LbListener_DefaultAction_AuthenticateOidc) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LbListener_DefaultAction_AuthenticateOidc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LbListener_DefaultAction_AuthenticateOidc.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LbListener_DefaultAction_AuthenticateOidc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LbListener_DefaultAction_AuthenticateOidc.Merge(m, src)
}
func (m *LbListener_DefaultAction_AuthenticateOidc) XXX_Size() int {
	return m.Size()
}
func (m *LbListener_DefaultAction_AuthenticateOidc) XXX_DiscardUnknown() {
	xxx_messageInfo_LbListener_DefaultAction_AuthenticateOidc.DiscardUnknown(m)
}

var xxx_messageInfo_LbListener_DefaultAction_AuthenticateOidc proto.InternalMessageInfo

func (m *LbListener_DefaultAction_AuthenticateOidc) GetAuthenticationRequestExtraParams() map[string]string {
	if m != nil {
		return m.AuthenticationRequestExtraParams
	}
	return nil
}

func (m *LbListener_DefaultAction_AuthenticateOidc) GetAuthorizationEndpoint() string {
	if m != nil {
		return m.AuthorizationEndpoint
	}
	return ""
}

func (m *LbListener_DefaultAction_AuthenticateOidc) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *LbListener_DefaultAction_AuthenticateOidc) GetClientSecret() string {
	if m != nil {
		return m.ClientSecret
	}
	return ""
}

func (m *LbListener_DefaultAction_AuthenticateOidc) GetIssuer() string {
	if m != nil {
		return m.Issuer
	}
	return ""
}

func (m *LbListener_DefaultAction_AuthenticateOidc) GetOnUnauthenticatedRequest() string {
	if m != nil {
		return m.OnUnauthenticatedRequest
	}
	return ""
}

func (m *LbListener_DefaultAction_AuthenticateOidc) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *LbListener_DefaultAction_AuthenticateOidc) GetSessionCookieName() string {
	if m != nil {
		return m.SessionCookieName
	}
	return ""
}

func (m *LbListener_DefaultAction_AuthenticateOidc) GetSessionTimeout() int64 {
	if m != nil {
		return m.SessionTimeout
	}
	return 0
}

func (m *LbListener_DefaultAction_AuthenticateOidc) GetTokenEndpoint() string {
	if m != nil {
		return m.TokenEndpoint
	}
	return ""
}

func (m *LbListener_DefaultAction_AuthenticateOidc) GetUserInfoEndpoint() string {
	if m != nil {
		return m.UserInfoEndpoint
	}
	return ""
}

type LbListener_DefaultAction_FixedResponse struct {
	ContentType string `protobuf:"bytes,1,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	MessageBody string `protobuf:"bytes,2,opt,name=message_body,json=messageBody,proto3" json:"message_body,omitempty"`
	StatusCode  string `protobuf:"bytes,3,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
}

func (m *LbListener_DefaultAction_FixedResponse) Reset() {
	*m = LbListener_DefaultAction_FixedResponse{}
}
func (m *LbListener_DefaultAction_FixedResponse) String() string { return proto.CompactTextString(m) }
func (*LbListener_DefaultAction_FixedResponse) ProtoMessage()    {}
func (*LbListener_DefaultAction_FixedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d2373b4195c780, []int{0, 0, 2}
}
func (m *LbListener_DefaultAction_FixedResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LbListener_DefaultAction_FixedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LbListener_DefaultAction_FixedResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LbListener_DefaultAction_FixedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LbListener_DefaultAction_FixedResponse.Merge(m, src)
}
func (m *LbListener_DefaultAction_FixedResponse) XXX_Size() int {
	return m.Size()
}
func (m *LbListener_DefaultAction_FixedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LbListener_DefaultAction_FixedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LbListener_DefaultAction_FixedResponse proto.InternalMessageInfo

func (m *LbListener_DefaultAction_FixedResponse) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *LbListener_DefaultAction_FixedResponse) GetMessageBody() string {
	if m != nil {
		return m.MessageBody
	}
	return ""
}

func (m *LbListener_DefaultAction_FixedResponse) GetStatusCode() string {
	if m != nil {
		return m.StatusCode
	}
	return ""
}

type LbListener_DefaultAction_Redirect struct {
	Host       string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Path       string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Port       string `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	Protocol   string `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Query      string `protobuf:"bytes,5,opt,name=query,proto3" json:"query,omitempty"`
	StatusCode string `protobuf:"bytes,6,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
}

func (m *LbListener_DefaultAction_Redirect) Reset()         { *m = LbListener_DefaultAction_Redirect{} }
func (m *LbListener_DefaultAction_Redirect) String() string { return proto.CompactTextString(m) }
func (*LbListener_DefaultAction_Redirect) ProtoMessage()    {}
func (*LbListener_DefaultAction_Redirect) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d2373b4195c780, []int{0, 0, 3}
}
func (m *LbListener_DefaultAction_Redirect) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LbListener_DefaultAction_Redirect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LbListener_DefaultAction_Redirect.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LbListener_DefaultAction_Redirect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LbListener_DefaultAction_Redirect.Merge(m, src)
}
func (m *LbListener_DefaultAction_Redirect) XXX_Size() int {
	return m.Size()
}
func (m *LbListener_DefaultAction_Redirect) XXX_DiscardUnknown() {
	xxx_messageInfo_LbListener_DefaultAction_Redirect.DiscardUnknown(m)
}

var xxx_messageInfo_LbListener_DefaultAction_Redirect proto.InternalMessageInfo

func (m *LbListener_DefaultAction_Redirect) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *LbListener_DefaultAction_Redirect) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *LbListener_DefaultAction_Redirect) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *LbListener_DefaultAction_Redirect) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *LbListener_DefaultAction_Redirect) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *LbListener_DefaultAction_Redirect) GetStatusCode() string {
	if m != nil {
		return m.StatusCode
	}
	return ""
}

func init() {
	proto.RegisterType((*LbListener)(nil), "terraform.aws.LbListener")
	proto.RegisterType((*LbListener_DefaultAction)(nil), "terraform.aws.LbListener.DefaultAction")
	proto.RegisterType((*LbListener_DefaultAction_AuthenticateCognito)(nil), "terraform.aws.LbListener.DefaultAction.AuthenticateCognito")
	proto.RegisterMapType((map[string]string)(nil), "terraform.aws.LbListener.DefaultAction.AuthenticateCognito.AuthenticationRequestExtraParamsEntry")
	proto.RegisterType((*LbListener_DefaultAction_AuthenticateOidc)(nil), "terraform.aws.LbListener.DefaultAction.AuthenticateOidc")
	proto.RegisterMapType((map[string]string)(nil), "terraform.aws.LbListener.DefaultAction.AuthenticateOidc.AuthenticationRequestExtraParamsEntry")
	proto.RegisterType((*LbListener_DefaultAction_FixedResponse)(nil), "terraform.aws.LbListener.DefaultAction.FixedResponse")
	proto.RegisterType((*LbListener_DefaultAction_Redirect)(nil), "terraform.aws.LbListener.DefaultAction.Redirect")
}

func init() { proto.RegisterFile("lb_listener.proto", fileDescriptor_56d2373b4195c780) }

var fileDescriptor_56d2373b4195c780 = []byte{
	// 903 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xd1, 0x6e, 0x1b, 0x45,
	0x14, 0xed, 0xc6, 0x89, 0x6b, 0x5f, 0xd7, 0x8e, 0x33, 0x09, 0xd5, 0xca, 0x08, 0x13, 0x5a, 0x55,
	0x8d, 0x10, 0x58, 0x08, 0x54, 0xa9, 0x02, 0x5e, 0x92, 0x34, 0xa0, 0x4a, 0x51, 0x89, 0xb6, 0xe5,
	0x0d, 0xb1, 0x1a, 0xef, 0x5e, 0x27, 0xa3, 0xac, 0xe7, 0x6e, 0x67, 0x66, 0x4b, 0xcd, 0x07, 0xf0,
	0xcc, 0x2b, 0xbf, 0x80, 0x84, 0xc4, 0x5f, 0xc0, 0x63, 0x1f, 0x79, 0x44, 0xc9, 0x17, 0xf0, 0x07,
	0x68, 0x66, 0x67, 0xe3, 0xb5, 0xa9, 0x54, 0xb7, 0xc0, 0xdb, 0xdc, 0x73, 0xef, 0xde, 0x33, 0x3b,
	0xe7, 0xcc, 0x1d, 0xd8, 0xca, 0xc6, 0x71, 0x26, 0xb4, 0x41, 0x89, 0x6a, 0x94, 0x2b, 0x32, 0xc4,
	0xba, 0x06, 0x95, 0xe2, 0x13, 0x52, 0xd3, 0x11, 0xff, 0x4e, 0xdf, 0xfa, 0x81, 0x01, 0x1c, 0x8f,
	0x8f, 0x7d, 0x0d, 0xeb, 0x43, 0x83, 0x2b, 0x19, 0x06, 0xbb, 0xc1, 0x5e, 0x3b, 0xb2, 0x4b, 0x76,
	0x17, 0x36, 0x13, 0x54, 0x46, 0x4c, 0x44, 0xc2, 0x0d, 0xc6, 0x36, 0xbb, 0xe6, 0xb2, 0xbd, 0x1a,
	0xbc, 0xaf, 0x24, 0x7b, 0x04, 0xbd, 0x14, 0x27, 0xbc, 0xc8, 0x4c, 0xcc, 0x13, 0x23, 0x48, 0x86,
	0x8d, 0xdd, 0xc6, 0x5e, 0xe7, 0xe3, 0xbb, 0xa3, 0x05, 0xc6, 0xd1, 0x9c, 0x6d, 0xf4, 0xa0, 0xac,
	0xdf, 0x77, 0xe5, 0x51, 0x37, 0xad, 0x87, 0xec, 0x7d, 0xd8, 0xca, 0x88, 0xa7, 0xf1, 0x98, 0x67,
	0x5c, 0x26, 0xa8, 0x1c, 0xf5, 0xba, 0xa3, 0xde, 0xb4, 0x89, 0x03, 0x8f, 0x5b, 0x6e, 0x06, 0xeb,
	0x39, 0x29, 0x13, 0x6e, 0xec, 0x06, 0x7b, 0x8d, 0xc8, 0xad, 0xd9, 0x00, 0x5a, 0xee, 0x8f, 0x13,
	0xca, 0xc2, 0xa6, 0xfb, 0xec, 0x2a, 0x66, 0xef, 0x00, 0x68, 0x9d, 0xc5, 0x39, 0x65, 0x22, 0x99,
	0x85, 0xd7, 0x5d, 0xb6, 0xad, 0x75, 0x76, 0xe2, 0x80, 0xc1, 0x5f, 0x9b, 0xd0, 0x5d, 0xd8, 0x1b,
	0x93, 0xb0, 0xc3, 0x0b, 0x73, 0x86, 0xd2, 0x94, 0xc7, 0x90, 0xd0, 0xa9, 0x14, 0x86, 0xc2, 0xc0,
	0xfd, 0xe2, 0x67, 0x2b, 0xfe, 0xe2, 0x68, 0xbf, 0xd6, 0xe3, 0xb0, 0x6c, 0x11, 0x6d, 0xf3, 0x7f,
	0x82, 0x0c, 0x61, 0x6b, 0x81, 0x8f, 0x44, 0x9a, 0x84, 0x6b, 0x8e, 0xec, 0xfe, 0x9b, 0x90, 0x7d,
	0x25, 0xd2, 0x24, 0xea, 0xf3, 0x25, 0x84, 0x7d, 0x03, 0xbd, 0x89, 0x78, 0x8e, 0x69, 0xac, 0x50,
	0xe7, 0x24, 0x35, 0x7a, 0xcd, 0xee, 0xad, 0xca, 0xf1, 0x85, 0xfd, 0x3a, 0xf2, 0x1f, 0x47, 0xdd,
	0x49, 0x3d, 0x64, 0x3b, 0xb0, 0x41, 0x2a, 0x45, 0xe5, 0x54, 0x6b, 0x44, 0x65, 0xc0, 0x8e, 0xa1,
	0xa5, 0x30, 0x15, 0x0a, 0x13, 0xab, 0x97, 0x65, 0xfb, 0x68, 0x55, 0xb6, 0xc8, 0x7f, 0x17, 0x5d,
	0x75, 0x60, 0x7b, 0xd0, 0x37, 0x5c, 0x9d, 0xa2, 0x89, 0x4f, 0x15, 0x15, 0xb9, 0x33, 0x49, 0xa9,
	0x76, 0xaf, 0xc4, 0xbf, 0xb4, 0xb0, 0xf7, 0x88, 0x99, 0xe5, 0xe8, 0xd5, 0x76, 0xeb, 0xc1, 0x6f,
	0xeb, 0xb0, 0xfd, 0x12, 0x4d, 0xd8, 0xaf, 0x01, 0xdc, 0xae, 0x1d, 0x96, 0x20, 0x19, 0x2b, 0x7c,
	0x5a, 0xa0, 0x36, 0x31, 0x3e, 0x37, 0x8a, 0xc7, 0x39, 0x57, 0x7c, 0xaa, 0xbd, 0xfc, 0xfc, 0x5f,
	0xc8, 0x5f, 0xc7, 0xec, 0x25, 0x28, 0x59, 0x8e, 0x2c, 0xc9, 0x89, 0xe3, 0x38, 0x92, 0x46, 0xcd,
	0xa2, 0x5d, 0xfe, 0x8a, 0x32, 0xf6, 0x39, 0x0c, 0x48, 0xc6, 0x85, 0xac, 0x6b, 0x9c, 0x56, 0xbb,
	0xf6, 0x57, 0x36, 0x24, 0xf9, 0xf5, 0x62, 0x81, 0x6f, 0x64, 0xa5, 0xd2, 0x09, 0xe5, 0x56, 0x7f,
	0x5b, 0x58, 0x06, 0x6c, 0x04, 0xdb, 0x1a, 0xb5, 0xb6, 0xbf, 0x9f, 0x10, 0x9d, 0x0b, 0x8c, 0x25,
	0x9f, 0xa2, 0xbf, 0x84, 0x5b, 0x3e, 0x75, 0xe8, 0x32, 0x8f, 0xf8, 0x14, 0xed, 0xac, 0xa8, 0xea,
	0x8d, 0x98, 0x22, 0x15, 0xd5, 0x8d, 0xec, 0x79, 0xf8, 0x49, 0x89, 0xb2, 0x5b, 0xd0, 0x2d, 0x34,
	0xaa, 0x38, 0x27, 0xca, 0x6a, 0x92, 0x75, 0x2c, 0x78, 0x42, 0x94, 0x59, 0xbd, 0x3e, 0x84, 0xed,
	0x79, 0x4d, 0x92, 0x09, 0x94, 0x26, 0x16, 0xa9, 0x97, 0xaf, 0x5f, 0x55, 0x1e, 0xba, 0xc4, 0xc3,
	0xd4, 0x1a, 0x61, 0x5e, 0x9e, 0xd2, 0x94, 0x0b, 0x19, 0xb6, 0x4a, 0x23, 0x54, 0xb5, 0x0f, 0x1c,
	0x3a, 0x78, 0x0c, 0x77, 0x56, 0x3a, 0x74, 0x3b, 0x0c, 0xcf, 0x71, 0x56, 0x0d, 0xc3, 0x73, 0x9c,
	0xd9, 0x63, 0x7a, 0xc6, 0xb3, 0x02, 0xfd, 0x79, 0x96, 0xc1, 0xa7, 0x6b, 0xf7, 0x83, 0xc1, 0xcf,
	0x1b, 0xd0, 0x5f, 0xbe, 0x70, 0xec, 0x97, 0xd7, 0xb2, 0xd1, 0xb7, 0x6f, 0x7a, 0xb1, 0xff, 0x33,
	0x0f, 0xdd, 0x83, 0x9b, 0xb6, 0x86, 0x94, 0xf8, 0xbe, 0xdc, 0x2d, 0xca, 0x34, 0x27, 0x21, 0x2b,
	0xff, 0xbc, 0xb5, 0x90, 0x3d, 0xf2, 0x49, 0xf6, 0x36, 0xb4, 0xe7, 0xfa, 0x94, 0x06, 0x6a, 0x25,
	0x95, 0x2e, 0xb7, 0xa1, 0xeb, 0x93, 0x1a, 0x13, 0x85, 0xc6, 0xbb, 0xe7, 0x46, 0x09, 0x3e, 0x76,
	0x18, 0xbb, 0x09, 0x4d, 0xa1, 0x75, 0x81, 0xca, 0xf9, 0xa5, 0x1d, 0xf9, 0xe8, 0x15, 0xa6, 0x6e,
	0xae, 0x6a, 0xea, 0xeb, 0x2b, 0x98, 0xba, 0xf5, 0x1a, 0xa6, 0x6e, 0xbf, 0xd4, 0xd4, 0x77, 0xa0,
	0x67, 0xe8, 0x1c, 0x6b, 0xa7, 0x06, 0xae, 0x67, 0xd7, 0xa1, 0x57, 0xa7, 0xf5, 0x01, 0x30, 0x67,
	0x54, 0x21, 0x27, 0x34, 0x2f, 0xed, 0xcc, 0x6d, 0xfd, 0x50, 0x4e, 0xa8, 0xaa, 0xfe, 0x7f, 0xcc,
	0xfa, 0x0c, 0xba, 0x0b, 0x83, 0x9b, 0xbd, 0x07, 0x37, 0x12, 0x92, 0xc6, 0xaa, 0xe4, 0x66, 0x64,
	0xd9, 0xa5, 0xe3, 0xb1, 0x27, 0xb3, 0xdc, 0x95, 0x4c, 0x51, 0x6b, 0x7e, 0x8a, 0xf1, 0x98, 0xd2,
	0x99, 0x6f, 0xda, 0xf1, 0xd8, 0x01, 0xa5, 0x33, 0xf6, 0x2e, 0x74, 0xb4, 0xe1, 0xa6, 0xd0, 0x71,
	0x42, 0x69, 0x35, 0x4a, 0xa0, 0x84, 0x0e, 0x29, 0xc5, 0xc1, 0x4f, 0x01, 0xb4, 0xaa, 0x19, 0x6e,
	0xe7, 0xf1, 0x19, 0x69, 0xe3, 0xb9, 0xdc, 0xda, 0xbd, 0xe3, 0xdc, 0x9c, 0xf9, 0xe6, 0x6e, 0x7d,
	0xf5, 0xb6, 0x37, 0x3c, 0xb6, 0xfc, 0xb6, 0xaf, 0x2f, 0xbd, 0xed, 0x3b, 0xb0, 0xf1, 0xb4, 0x40,
	0x35, 0xf3, 0x56, 0x2a, 0x83, 0xe5, 0xbd, 0x35, 0x97, 0xf7, 0x76, 0x10, 0xfe, 0x7e, 0x31, 0x0c,
	0x5e, 0x5c, 0x0c, 0x83, 0x3f, 0x2f, 0x86, 0xc1, 0x8f, 0x97, 0xc3, 0x6b, 0x2f, 0x2e, 0x87, 0xd7,
	0xfe, 0xb8, 0x1c, 0x5e, 0x1b, 0x37, 0x5d, 0xeb, 0x4f, 0xfe, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x41,
	0xf1, 0xf5, 0x00, 0x4d, 0x09, 0x00, 0x00,
}

func (m *LbListener) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LbListener) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Arn) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintLbListener(dAtA, i, uint64(len(m.Arn)))
		i += copy(dAtA[i:], m.Arn)
	}
	if len(m.CertificateArn) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintLbListener(dAtA, i, uint64(len(m.CertificateArn)))
		i += copy(dAtA[i:], m.CertificateArn)
	}
	if len(m.DefaultAction) > 0 {
		for _, msg := range m.DefaultAction {
			dAtA[i] = 0x1a
			i++
			i = encodeVarintLbListener(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.LoadBalancerArn) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintLbListener(dAtA, i, uint64(len(m.LoadBalancerArn)))
		i += copy(dAtA[i:], m.LoadBalancerArn)
	}
	if m.Port != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintLbListener(dAtA, i, uint64(m.Port))
	}
	if len(m.Protocol) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintLbListener(dAtA, i, uint64(len(m.Protocol)))
		i += copy(dAtA[i:], m.Protocol)
	}
	if len(m.SslPolicy) > 0 {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintLbListener(dAtA, i, uint64(len(m.SslPolicy)))
		i += copy(dAtA[i:], m.SslPolicy)
	}
	return i, nil
}

func (m *LbListener_DefaultAction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LbListener_DefaultAction) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.AuthenticateCognito) > 0 {
		for _, msg := range m.AuthenticateCognito {
			dAtA[i] = 0xa
			i++
			i = encodeVarintLbListener(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.AuthenticateOidc) > 0 {
		for _, msg := range m.AuthenticateOidc {
			dAtA[i] = 0x12
			i++
			i = encodeVarintLbListener(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.FixedResponse) > 0 {
		for _, msg := range m.FixedResponse {
			dAtA[i] = 0x1a
			i++
			i = encodeVarintLbListener(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.Order != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintLbListener(dAtA, i, uint64(m.Order))
	}
	if len(m.Redirect) > 0 {
		for _, msg := range m.Redirect {
			dAtA[i] = 0x2a
			i++
			i = encodeVarintLbListener(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.TargetGroupArn) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintLbListener(dAtA, i, uint64(len(m.TargetGroupArn)))
		i += copy(dAtA[i:], m.TargetGroupArn)
	}
	if len(m.Type) > 0 {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintLbListener(dAtA, i, uint64(len(m.Type)))
		i += copy(dAtA[i:], m.Type)
	}
	return i, nil
}

func (m *LbListener_DefaultAction_AuthenticateCognito) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LbListener_DefaultAction_AuthenticateCognito) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.AuthenticationRequestExtraParams) > 0 {
		for k, _ := range m.AuthenticationRequestExtraParams {
			dAtA[i] = 0xa
			i++
			v := m.AuthenticationRequestExtraParams[k]
			mapSize := 1 + len(k) + sovLbListener(uint64(len(k))) + 1 + len(v) + sovLbListener(uint64(len(v)))
			i = encodeVarintLbListener(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintLbListener(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			dAtA[i] = 0x12
			i++
			i = encodeVarintLbListener(dAtA, i, uint64(len(v)))
			i += copy(dAtA[i:], v)
		}
	}
	if len(m.OnUnauthenticatedRequest) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintLbListener(dAtA, i, uint64(len(m.OnUnauthenticatedRequest)))
		i += copy(dAtA[i:], m.OnUnauthenticatedRequest)
	}
	if len(m.Scope) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintLbListener(dAtA, i, uint64(len(m.Scope)))
		i += copy(dAtA[i:], m.Scope)
	}
	if len(m.SessionCookieName) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintLbListener(dAtA, i, uint64(len(m.SessionCookieName)))
		i += copy(dAtA[i:], m.SessionCookieName)
	}
	if m.SessionTimeout != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintLbListener(dAtA, i, uint64(m.SessionTimeout))
	}
	if len(m.UserPoolArn) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintLbListener(dAtA, i, uint64(len(m.UserPoolArn)))
		i += copy(dAtA[i:], m.UserPoolArn)
	}
	if len(m.UserPoolClientId) > 0 {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintLbListener(dAtA, i, uint64(len(m.UserPoolClientId)))
		i += copy(dAtA[i:], m.UserPoolClientId)
	}
	if len(m.UserPoolDomain) > 0 {
		dAtA[i] = 0x42
		i++
		i = encodeVarintLbListener(dAtA, i, uint64(len(m.UserPoolDomain)))
		i += copy(dAtA[i:], m.UserPoolDomain)
	}
	return i, nil
}

func (m *LbListener_DefaultAction_AuthenticateOidc) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LbListener_DefaultAction_AuthenticateOidc) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.AuthenticationRequestExtraParams) > 0 {
		for k, _ := range m.AuthenticationRequestExtraParams {
			dAtA[i] = 0xa
			i++
			v := m.AuthenticationRequestExtraParams[k]
			mapSize := 1 + len(k) + sovLbListener(uint64(len(k))) + 1 + len(v) + sovLbListener(uint64(len(v)))
			i = encodeVarintLbListener(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintLbListener(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			dAtA[i] = 0x12
			i++
			i = encodeVarintLbListener(dAtA, i, uint64(len(v)))
			i += copy(dAtA[i:], v)
		}
	}
	if len(m.AuthorizationEndpoint) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintLbListener(dAtA, i, uint64(len(m.AuthorizationEndpoint)))
		i += copy(dAtA[i:], m.AuthorizationEndpoint)
	}
	if len(m.ClientId) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintLbListener(dAtA, i, uint64(len(m.ClientId)))
		i += copy(dAtA[i:], m.ClientId)
	}
	if len(m.ClientSecret) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintLbListener(dAtA, i, uint64(len(m.ClientSecret)))
		i += copy(dAtA[i:], m.ClientSecret)
	}
	if len(m.Issuer) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintLbListener(dAtA, i, uint64(len(m.Issuer)))
		i += copy(dAtA[i:], m.Issuer)
	}
	if len(m.OnUnauthenticatedRequest) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintLbListener(dAtA, i, uint64(len(m.OnUnauthenticatedRequest)))
		i += copy(dAtA[i:], m.OnUnauthenticatedRequest)
	}
	if len(m.Scope) > 0 {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintLbListener(dAtA, i, uint64(len(m.Scope)))
		i += copy(dAtA[i:], m.Scope)
	}
	if len(m.SessionCookieName) > 0 {
		dAtA[i] = 0x42
		i++
		i = encodeVarintLbListener(dAtA, i, uint64(len(m.SessionCookieName)))
		i += copy(dAtA[i:], m.SessionCookieName)
	}
	if m.SessionTimeout != 0 {
		dAtA[i] = 0x48
		i++
		i = encodeVarintLbListener(dAtA, i, uint64(m.SessionTimeout))
	}
	if len(m.TokenEndpoint) > 0 {
		dAtA[i] = 0x52
		i++
		i = encodeVarintLbListener(dAtA, i, uint64(len(m.TokenEndpoint)))
		i += copy(dAtA[i:], m.TokenEndpoint)
	}
	if len(m.UserInfoEndpoint) > 0 {
		dAtA[i] = 0x5a
		i++
		i = encodeVarintLbListener(dAtA, i, uint64(len(m.UserInfoEndpoint)))
		i += copy(dAtA[i:], m.UserInfoEndpoint)
	}
	return i, nil
}

func (m *LbListener_DefaultAction_FixedResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LbListener_DefaultAction_FixedResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.ContentType) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintLbListener(dAtA, i, uint64(len(m.ContentType)))
		i += copy(dAtA[i:], m.ContentType)
	}
	if len(m.MessageBody) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintLbListener(dAtA, i, uint64(len(m.MessageBody)))
		i += copy(dAtA[i:], m.MessageBody)
	}
	if len(m.StatusCode) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintLbListener(dAtA, i, uint64(len(m.StatusCode)))
		i += copy(dAtA[i:], m.StatusCode)
	}
	return i, nil
}

func (m *LbListener_DefaultAction_Redirect) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LbListener_DefaultAction_Redirect) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Host) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintLbListener(dAtA, i, uint64(len(m.Host)))
		i += copy(dAtA[i:], m.Host)
	}
	if len(m.Path) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintLbListener(dAtA, i, uint64(len(m.Path)))
		i += copy(dAtA[i:], m.Path)
	}
	if len(m.Port) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintLbListener(dAtA, i, uint64(len(m.Port)))
		i += copy(dAtA[i:], m.Port)
	}
	if len(m.Protocol) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintLbListener(dAtA, i, uint64(len(m.Protocol)))
		i += copy(dAtA[i:], m.Protocol)
	}
	if len(m.Query) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintLbListener(dAtA, i, uint64(len(m.Query)))
		i += copy(dAtA[i:], m.Query)
	}
	if len(m.StatusCode) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintLbListener(dAtA, i, uint64(len(m.StatusCode)))
		i += copy(dAtA[i:], m.StatusCode)
	}
	return i, nil
}

func encodeVarintLbListener(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *LbListener) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Arn)
	if l > 0 {
		n += 1 + l + sovLbListener(uint64(l))
	}
	l = len(m.CertificateArn)
	if l > 0 {
		n += 1 + l + sovLbListener(uint64(l))
	}
	if len(m.DefaultAction) > 0 {
		for _, e := range m.DefaultAction {
			l = e.Size()
			n += 1 + l + sovLbListener(uint64(l))
		}
	}
	l = len(m.LoadBalancerArn)
	if l > 0 {
		n += 1 + l + sovLbListener(uint64(l))
	}
	if m.Port != 0 {
		n += 1 + sovLbListener(uint64(m.Port))
	}
	l = len(m.Protocol)
	if l > 0 {
		n += 1 + l + sovLbListener(uint64(l))
	}
	l = len(m.SslPolicy)
	if l > 0 {
		n += 1 + l + sovLbListener(uint64(l))
	}
	return n
}

func (m *LbListener_DefaultAction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.AuthenticateCognito) > 0 {
		for _, e := range m.AuthenticateCognito {
			l = e.Size()
			n += 1 + l + sovLbListener(uint64(l))
		}
	}
	if len(m.AuthenticateOidc) > 0 {
		for _, e := range m.AuthenticateOidc {
			l = e.Size()
			n += 1 + l + sovLbListener(uint64(l))
		}
	}
	if len(m.FixedResponse) > 0 {
		for _, e := range m.FixedResponse {
			l = e.Size()
			n += 1 + l + sovLbListener(uint64(l))
		}
	}
	if m.Order != 0 {
		n += 1 + sovLbListener(uint64(m.Order))
	}
	if len(m.Redirect) > 0 {
		for _, e := range m.Redirect {
			l = e.Size()
			n += 1 + l + sovLbListener(uint64(l))
		}
	}
	l = len(m.TargetGroupArn)
	if l > 0 {
		n += 1 + l + sovLbListener(uint64(l))
	}
	l = len(m.Type)
	if l > 0 {
		n += 1 + l + sovLbListener(uint64(l))
	}
	return n
}

func (m *LbListener_DefaultAction_AuthenticateCognito) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.AuthenticationRequestExtraParams) > 0 {
		for k, v := range m.AuthenticationRequestExtraParams {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovLbListener(uint64(len(k))) + 1 + len(v) + sovLbListener(uint64(len(v)))
			n += mapEntrySize + 1 + sovLbListener(uint64(mapEntrySize))
		}
	}
	l = len(m.OnUnauthenticatedRequest)
	if l > 0 {
		n += 1 + l + sovLbListener(uint64(l))
	}
	l = len(m.Scope)
	if l > 0 {
		n += 1 + l + sovLbListener(uint64(l))
	}
	l = len(m.SessionCookieName)
	if l > 0 {
		n += 1 + l + sovLbListener(uint64(l))
	}
	if m.SessionTimeout != 0 {
		n += 1 + sovLbListener(uint64(m.SessionTimeout))
	}
	l = len(m.UserPoolArn)
	if l > 0 {
		n += 1 + l + sovLbListener(uint64(l))
	}
	l = len(m.UserPoolClientId)
	if l > 0 {
		n += 1 + l + sovLbListener(uint64(l))
	}
	l = len(m.UserPoolDomain)
	if l > 0 {
		n += 1 + l + sovLbListener(uint64(l))
	}
	return n
}

func (m *LbListener_DefaultAction_AuthenticateOidc) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.AuthenticationRequestExtraParams) > 0 {
		for k, v := range m.AuthenticationRequestExtraParams {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovLbListener(uint64(len(k))) + 1 + len(v) + sovLbListener(uint64(len(v)))
			n += mapEntrySize + 1 + sovLbListener(uint64(mapEntrySize))
		}
	}
	l = len(m.AuthorizationEndpoint)
	if l > 0 {
		n += 1 + l + sovLbListener(uint64(l))
	}
	l = len(m.ClientId)
	if l > 0 {
		n += 1 + l + sovLbListener(uint64(l))
	}
	l = len(m.ClientSecret)
	if l > 0 {
		n += 1 + l + sovLbListener(uint64(l))
	}
	l = len(m.Issuer)
	if l > 0 {
		n += 1 + l + sovLbListener(uint64(l))
	}
	l = len(m.OnUnauthenticatedRequest)
	if l > 0 {
		n += 1 + l + sovLbListener(uint64(l))
	}
	l = len(m.Scope)
	if l > 0 {
		n += 1 + l + sovLbListener(uint64(l))
	}
	l = len(m.SessionCookieName)
	if l > 0 {
		n += 1 + l + sovLbListener(uint64(l))
	}
	if m.SessionTimeout != 0 {
		n += 1 + sovLbListener(uint64(m.SessionTimeout))
	}
	l = len(m.TokenEndpoint)
	if l > 0 {
		n += 1 + l + sovLbListener(uint64(l))
	}
	l = len(m.UserInfoEndpoint)
	if l > 0 {
		n += 1 + l + sovLbListener(uint64(l))
	}
	return n
}

func (m *LbListener_DefaultAction_FixedResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ContentType)
	if l > 0 {
		n += 1 + l + sovLbListener(uint64(l))
	}
	l = len(m.MessageBody)
	if l > 0 {
		n += 1 + l + sovLbListener(uint64(l))
	}
	l = len(m.StatusCode)
	if l > 0 {
		n += 1 + l + sovLbListener(uint64(l))
	}
	return n
}

func (m *LbListener_DefaultAction_Redirect) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Host)
	if l > 0 {
		n += 1 + l + sovLbListener(uint64(l))
	}
	l = len(m.Path)
	if l > 0 {
		n += 1 + l + sovLbListener(uint64(l))
	}
	l = len(m.Port)
	if l > 0 {
		n += 1 + l + sovLbListener(uint64(l))
	}
	l = len(m.Protocol)
	if l > 0 {
		n += 1 + l + sovLbListener(uint64(l))
	}
	l = len(m.Query)
	if l > 0 {
		n += 1 + l + sovLbListener(uint64(l))
	}
	l = len(m.StatusCode)
	if l > 0 {
		n += 1 + l + sovLbListener(uint64(l))
	}
	return n
}

func sovLbListener(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozLbListener(x uint64) (n int) {
	return sovLbListener(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *LbListener) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLbListener
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LbListener: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LbListener: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Arn", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbListener
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLbListener
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLbListener
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Arn = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CertificateArn", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbListener
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLbListener
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLbListener
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CertificateArn = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefaultAction", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbListener
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLbListener
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLbListener
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DefaultAction = append(m.DefaultAction, &LbListener_DefaultAction{})
			if err := m.DefaultAction[len(m.DefaultAction)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LoadBalancerArn", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbListener
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLbListener
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLbListener
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LoadBalancerArn = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Port", wireType)
			}
			m.Port = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbListener
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Port |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Protocol", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbListener
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLbListener
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLbListener
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Protocol = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SslPolicy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbListener
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLbListener
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLbListener
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SslPolicy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLbListener(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthLbListener
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthLbListener
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LbListener_DefaultAction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLbListener
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DefaultAction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DefaultAction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthenticateCognito", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbListener
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLbListener
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLbListener
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuthenticateCognito = append(m.AuthenticateCognito, &LbListener_DefaultAction_AuthenticateCognito{})
			if err := m.AuthenticateCognito[len(m.AuthenticateCognito)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthenticateOidc", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbListener
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLbListener
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLbListener
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuthenticateOidc = append(m.AuthenticateOidc, &LbListener_DefaultAction_AuthenticateOidc{})
			if err := m.AuthenticateOidc[len(m.AuthenticateOidc)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FixedResponse", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbListener
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLbListener
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLbListener
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FixedResponse = append(m.FixedResponse, &LbListener_DefaultAction_FixedResponse{})
			if err := m.FixedResponse[len(m.FixedResponse)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Order", wireType)
			}
			m.Order = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbListener
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Order |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Redirect", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbListener
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLbListener
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLbListener
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Redirect = append(m.Redirect, &LbListener_DefaultAction_Redirect{})
			if err := m.Redirect[len(m.Redirect)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetGroupArn", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbListener
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLbListener
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLbListener
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TargetGroupArn = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbListener
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLbListener
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLbListener
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Type = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLbListener(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthLbListener
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthLbListener
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LbListener_DefaultAction_AuthenticateCognito) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLbListener
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AuthenticateCognito: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AuthenticateCognito: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthenticationRequestExtraParams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbListener
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLbListener
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLbListener
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.AuthenticationRequestExtraParams == nil {
				m.AuthenticationRequestExtraParams = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowLbListener
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowLbListener
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthLbListener
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthLbListener
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowLbListener
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthLbListener
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthLbListener
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipLbListener(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthLbListener
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.AuthenticationRequestExtraParams[mapkey] = mapvalue
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OnUnauthenticatedRequest", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbListener
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLbListener
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLbListener
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OnUnauthenticatedRequest = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Scope", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbListener
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLbListener
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLbListener
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Scope = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SessionCookieName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbListener
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLbListener
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLbListener
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SessionCookieName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SessionTimeout", wireType)
			}
			m.SessionTimeout = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbListener
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SessionTimeout |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserPoolArn", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbListener
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLbListener
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLbListener
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserPoolArn = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserPoolClientId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbListener
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLbListener
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLbListener
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserPoolClientId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserPoolDomain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbListener
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLbListener
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLbListener
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserPoolDomain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLbListener(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthLbListener
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthLbListener
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LbListener_DefaultAction_AuthenticateOidc) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLbListener
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AuthenticateOidc: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AuthenticateOidc: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthenticationRequestExtraParams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbListener
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLbListener
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLbListener
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.AuthenticationRequestExtraParams == nil {
				m.AuthenticationRequestExtraParams = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowLbListener
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowLbListener
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthLbListener
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthLbListener
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowLbListener
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthLbListener
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthLbListener
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipLbListener(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthLbListener
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.AuthenticationRequestExtraParams[mapkey] = mapvalue
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthorizationEndpoint", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbListener
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLbListener
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLbListener
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuthorizationEndpoint = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbListener
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLbListener
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLbListener
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientSecret", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbListener
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLbListener
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLbListener
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientSecret = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Issuer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbListener
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLbListener
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLbListener
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Issuer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OnUnauthenticatedRequest", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbListener
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLbListener
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLbListener
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OnUnauthenticatedRequest = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Scope", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbListener
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLbListener
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLbListener
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Scope = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SessionCookieName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbListener
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLbListener
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLbListener
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SessionCookieName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SessionTimeout", wireType)
			}
			m.SessionTimeout = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbListener
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SessionTimeout |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenEndpoint", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbListener
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLbListener
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLbListener
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TokenEndpoint = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserInfoEndpoint", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbListener
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLbListener
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLbListener
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserInfoEndpoint = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLbListener(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthLbListener
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthLbListener
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LbListener_DefaultAction_FixedResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLbListener
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FixedResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FixedResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContentType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbListener
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLbListener
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLbListener
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContentType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageBody", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbListener
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLbListener
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLbListener
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MessageBody = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StatusCode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbListener
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLbListener
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLbListener
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StatusCode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLbListener(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthLbListener
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthLbListener
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LbListener_DefaultAction_Redirect) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLbListener
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Redirect: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Redirect: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Host", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbListener
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLbListener
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLbListener
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Host = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Path", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbListener
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLbListener
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLbListener
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Path = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Port", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbListener
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLbListener
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLbListener
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Port = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Protocol", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbListener
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLbListener
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLbListener
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Protocol = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Query", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbListener
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLbListener
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLbListener
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Query = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StatusCode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbListener
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLbListener
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLbListener
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StatusCode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLbListener(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthLbListener
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthLbListener
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLbListener(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLbListener
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLbListener
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLbListener
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLbListener
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthLbListener
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowLbListener
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipLbListener(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthLbListener
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthLbListener = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLbListener   = fmt.Errorf("proto: integer overflow")
)
