// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lb_ssl_negotiation_policy.proto

package terraform_aws

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type LbSslNegotiationPolicy struct {
	Attribute    []*LbSslNegotiationPolicy_Attribute `protobuf:"bytes,1,rep,name=attribute,proto3" json:"attribute,omitempty"`
	LbPort       int64                               `protobuf:"varint,2,opt,name=lb_port,json=lbPort,proto3" json:"lb_port,omitempty"`
	LoadBalancer string                              `protobuf:"bytes,3,opt,name=load_balancer,json=loadBalancer,proto3" json:"load_balancer,omitempty"`
	Name         string                              `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
}

func (m *LbSslNegotiationPolicy) Reset()         { *m = LbSslNegotiationPolicy{} }
func (m *LbSslNegotiationPolicy) String() string { return proto.CompactTextString(m) }
func (*LbSslNegotiationPolicy) ProtoMessage()    {}
func (*LbSslNegotiationPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_36d46ae3602916b2, []int{0}
}
func (m *LbSslNegotiationPolicy) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LbSslNegotiationPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LbSslNegotiationPolicy.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LbSslNegotiationPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LbSslNegotiationPolicy.Merge(m, src)
}
func (m *LbSslNegotiationPolicy) XXX_Size() int {
	return m.Size()
}
func (m *LbSslNegotiationPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_LbSslNegotiationPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_LbSslNegotiationPolicy proto.InternalMessageInfo

func (m *LbSslNegotiationPolicy) GetAttribute() []*LbSslNegotiationPolicy_Attribute {
	if m != nil {
		return m.Attribute
	}
	return nil
}

func (m *LbSslNegotiationPolicy) GetLbPort() int64 {
	if m != nil {
		return m.LbPort
	}
	return 0
}

func (m *LbSslNegotiationPolicy) GetLoadBalancer() string {
	if m != nil {
		return m.LoadBalancer
	}
	return ""
}

func (m *LbSslNegotiationPolicy) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type LbSslNegotiationPolicy_Attribute struct {
	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *LbSslNegotiationPolicy_Attribute) Reset()         { *m = LbSslNegotiationPolicy_Attribute{} }
func (m *LbSslNegotiationPolicy_Attribute) String() string { return proto.CompactTextString(m) }
func (*LbSslNegotiationPolicy_Attribute) ProtoMessage()    {}
func (*LbSslNegotiationPolicy_Attribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_36d46ae3602916b2, []int{0, 0}
}
func (m *LbSslNegotiationPolicy_Attribute) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LbSslNegotiationPolicy_Attribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LbSslNegotiationPolicy_Attribute.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LbSslNegotiationPolicy_Attribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LbSslNegotiationPolicy_Attribute.Merge(m, src)
}
func (m *LbSslNegotiationPolicy_Attribute) XXX_Size() int {
	return m.Size()
}
func (m *LbSslNegotiationPolicy_Attribute) XXX_DiscardUnknown() {
	xxx_messageInfo_LbSslNegotiationPolicy_Attribute.DiscardUnknown(m)
}

var xxx_messageInfo_LbSslNegotiationPolicy_Attribute proto.InternalMessageInfo

func (m *LbSslNegotiationPolicy_Attribute) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LbSslNegotiationPolicy_Attribute) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*LbSslNegotiationPolicy)(nil), "terraform.aws.LbSslNegotiationPolicy")
	proto.RegisterType((*LbSslNegotiationPolicy_Attribute)(nil), "terraform.aws.LbSslNegotiationPolicy.Attribute")
}

func init() { proto.RegisterFile("lb_ssl_negotiation_policy.proto", fileDescriptor_36d46ae3602916b2) }

var fileDescriptor_36d46ae3602916b2 = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xcf, 0x49, 0x8a, 0x2f,
	0x2e, 0xce, 0x89, 0xcf, 0x4b, 0x4d, 0xcf, 0x2f, 0xc9, 0x4c, 0x2c, 0xc9, 0xcc, 0xcf, 0x8b, 0x2f,
	0xc8, 0xcf, 0xc9, 0x4c, 0xae, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2d, 0x49, 0x2d,
	0x2a, 0x4a, 0x4c, 0xcb, 0x2f, 0xca, 0xd5, 0x4b, 0x2c, 0x2f, 0x56, 0xfa, 0xc0, 0xc8, 0x25, 0xe6,
	0x93, 0x14, 0x5c, 0x9c, 0xe3, 0x87, 0xd0, 0x10, 0x00, 0x56, 0x2f, 0xe4, 0xcb, 0xc5, 0x99, 0x58,
	0x52, 0x52, 0x94, 0x99, 0x54, 0x5a, 0x92, 0x2a, 0xc1, 0xa8, 0xc0, 0xac, 0xc1, 0x6d, 0xa4, 0xaf,
	0x87, 0xa2, 0x5b, 0x0f, 0xbb, 0x4e, 0x3d, 0x47, 0x98, 0xb6, 0x20, 0x84, 0x09, 0x42, 0xe2, 0x5c,
	0xec, 0x39, 0x49, 0xf1, 0x05, 0xf9, 0x45, 0x25, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xcc, 0x41, 0x6c,
	0x39, 0x49, 0x01, 0xf9, 0x45, 0x25, 0x42, 0xca, 0x5c, 0xbc, 0x39, 0xf9, 0x89, 0x29, 0xf1, 0x49,
	0x89, 0x39, 0x89, 0x79, 0xc9, 0xa9, 0x45, 0x12, 0xcc, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x3c, 0x20,
	0x41, 0x27, 0xa8, 0x98, 0x90, 0x10, 0x17, 0x4b, 0x5e, 0x62, 0x6e, 0xaa, 0x04, 0x0b, 0x58, 0x0e,
	0xcc, 0x96, 0x32, 0xe5, 0xe2, 0x84, 0xdb, 0x04, 0x57, 0xc0, 0x88, 0x50, 0x20, 0x24, 0xc2, 0xc5,
	0x5a, 0x96, 0x98, 0x53, 0x9a, 0x0a, 0xb6, 0x90, 0x33, 0x08, 0xc2, 0x71, 0x92, 0x38, 0xf1, 0x48,
	0x8e, 0xf1, 0xc2, 0x23, 0x39, 0xc6, 0x07, 0x8f, 0xe4, 0x18, 0x27, 0x3c, 0x96, 0x63, 0xb8, 0xf0,
	0x58, 0x8e, 0xe1, 0xc6, 0x63, 0x39, 0x86, 0x24, 0x36, 0x70, 0x10, 0x19, 0x03, 0x02, 0x00, 0x00,
	0xff, 0xff, 0xca, 0xec, 0x45, 0x43, 0x45, 0x01, 0x00, 0x00,
}

func (m *LbSslNegotiationPolicy) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LbSslNegotiationPolicy) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Attribute) > 0 {
		for _, msg := range m.Attribute {
			dAtA[i] = 0xa
			i++
			i = encodeVarintLbSslNegotiationPolicy(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.LbPort != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintLbSslNegotiationPolicy(dAtA, i, uint64(m.LbPort))
	}
	if len(m.LoadBalancer) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintLbSslNegotiationPolicy(dAtA, i, uint64(len(m.LoadBalancer)))
		i += copy(dAtA[i:], m.LoadBalancer)
	}
	if len(m.Name) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintLbSslNegotiationPolicy(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	return i, nil
}

func (m *LbSslNegotiationPolicy_Attribute) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LbSslNegotiationPolicy_Attribute) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintLbSslNegotiationPolicy(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if len(m.Value) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintLbSslNegotiationPolicy(dAtA, i, uint64(len(m.Value)))
		i += copy(dAtA[i:], m.Value)
	}
	return i, nil
}

func encodeVarintLbSslNegotiationPolicy(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *LbSslNegotiationPolicy) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Attribute) > 0 {
		for _, e := range m.Attribute {
			l = e.Size()
			n += 1 + l + sovLbSslNegotiationPolicy(uint64(l))
		}
	}
	if m.LbPort != 0 {
		n += 1 + sovLbSslNegotiationPolicy(uint64(m.LbPort))
	}
	l = len(m.LoadBalancer)
	if l > 0 {
		n += 1 + l + sovLbSslNegotiationPolicy(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovLbSslNegotiationPolicy(uint64(l))
	}
	return n
}

func (m *LbSslNegotiationPolicy_Attribute) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovLbSslNegotiationPolicy(uint64(l))
	}
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovLbSslNegotiationPolicy(uint64(l))
	}
	return n
}

func sovLbSslNegotiationPolicy(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozLbSslNegotiationPolicy(x uint64) (n int) {
	return sovLbSslNegotiationPolicy(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *LbSslNegotiationPolicy) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLbSslNegotiationPolicy
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LbSslNegotiationPolicy: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LbSslNegotiationPolicy: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Attribute", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbSslNegotiationPolicy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLbSslNegotiationPolicy
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLbSslNegotiationPolicy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Attribute = append(m.Attribute, &LbSslNegotiationPolicy_Attribute{})
			if err := m.Attribute[len(m.Attribute)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LbPort", wireType)
			}
			m.LbPort = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbSslNegotiationPolicy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LbPort |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LoadBalancer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbSslNegotiationPolicy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLbSslNegotiationPolicy
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLbSslNegotiationPolicy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LoadBalancer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbSslNegotiationPolicy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLbSslNegotiationPolicy
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLbSslNegotiationPolicy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLbSslNegotiationPolicy(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthLbSslNegotiationPolicy
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthLbSslNegotiationPolicy
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LbSslNegotiationPolicy_Attribute) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLbSslNegotiationPolicy
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Attribute: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Attribute: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbSslNegotiationPolicy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLbSslNegotiationPolicy
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLbSslNegotiationPolicy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbSslNegotiationPolicy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLbSslNegotiationPolicy
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLbSslNegotiationPolicy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLbSslNegotiationPolicy(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthLbSslNegotiationPolicy
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthLbSslNegotiationPolicy
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLbSslNegotiationPolicy(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLbSslNegotiationPolicy
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLbSslNegotiationPolicy
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLbSslNegotiationPolicy
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLbSslNegotiationPolicy
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthLbSslNegotiationPolicy
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowLbSslNegotiationPolicy
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipLbSslNegotiationPolicy(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthLbSslNegotiationPolicy
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthLbSslNegotiationPolicy = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLbSslNegotiationPolicy   = fmt.Errorf("proto: integer overflow")
)
