// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lb_target_group_attachment.proto

package terraform_aws

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type LbTargetGroupAttachment struct {
	AvailabilityZone string `protobuf:"bytes,1,opt,name=availability_zone,json=availabilityZone,proto3" json:"availability_zone,omitempty"`
	Port             int64  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	TargetGroupArn   string `protobuf:"bytes,3,opt,name=target_group_arn,json=targetGroupArn,proto3" json:"target_group_arn,omitempty"`
	TargetId         string `protobuf:"bytes,4,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
}

func (m *LbTargetGroupAttachment) Reset()         { *m = LbTargetGroupAttachment{} }
func (m *LbTargetGroupAttachment) String() string { return proto.CompactTextString(m) }
func (*LbTargetGroupAttachment) ProtoMessage()    {}
func (*LbTargetGroupAttachment) Descriptor() ([]byte, []int) {
	return fileDescriptor_fadde9622c267e7b, []int{0}
}
func (m *LbTargetGroupAttachment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LbTargetGroupAttachment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LbTargetGroupAttachment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LbTargetGroupAttachment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LbTargetGroupAttachment.Merge(m, src)
}
func (m *LbTargetGroupAttachment) XXX_Size() int {
	return m.Size()
}
func (m *LbTargetGroupAttachment) XXX_DiscardUnknown() {
	xxx_messageInfo_LbTargetGroupAttachment.DiscardUnknown(m)
}

var xxx_messageInfo_LbTargetGroupAttachment proto.InternalMessageInfo

func (m *LbTargetGroupAttachment) GetAvailabilityZone() string {
	if m != nil {
		return m.AvailabilityZone
	}
	return ""
}

func (m *LbTargetGroupAttachment) GetPort() int64 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *LbTargetGroupAttachment) GetTargetGroupArn() string {
	if m != nil {
		return m.TargetGroupArn
	}
	return ""
}

func (m *LbTargetGroupAttachment) GetTargetId() string {
	if m != nil {
		return m.TargetId
	}
	return ""
}

func init() {
	proto.RegisterType((*LbTargetGroupAttachment)(nil), "terraform.aws.LbTargetGroupAttachment")
}

func init() { proto.RegisterFile("lb_target_group_attachment.proto", fileDescriptor_fadde9622c267e7b) }

var fileDescriptor_fadde9622c267e7b = []byte{
	// 209 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0xc8, 0x49, 0x8a, 0x2f,
	0x49, 0x2c, 0x4a, 0x4f, 0x2d, 0x89, 0x4f, 0x2f, 0xca, 0x2f, 0x2d, 0x88, 0x4f, 0x2c, 0x29, 0x49,
	0x4c, 0xce, 0xc8, 0x4d, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2d, 0x49,
	0x2d, 0x2a, 0x4a, 0x4c, 0xcb, 0x2f, 0xca, 0xd5, 0x4b, 0x2c, 0x2f, 0x56, 0x5a, 0xc8, 0xc8, 0x25,
	0xee, 0x93, 0x14, 0x02, 0xd6, 0xe2, 0x0e, 0xd2, 0xe1, 0x08, 0xd7, 0x20, 0xa4, 0xcd, 0x25, 0x98,
	0x58, 0x96, 0x98, 0x99, 0x93, 0x98, 0x94, 0x99, 0x93, 0x59, 0x52, 0x19, 0x5f, 0x95, 0x9f, 0x97,
	0x2a, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x24, 0x80, 0x2c, 0x11, 0x95, 0x9f, 0x97, 0x2a, 0x24,
	0xc4, 0xc5, 0x52, 0x90, 0x5f, 0x54, 0x22, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x1c, 0x04, 0x66, 0x0b,
	0x69, 0x70, 0x09, 0xa0, 0x3a, 0xa6, 0x28, 0x4f, 0x82, 0x19, 0xac, 0x9f, 0xaf, 0x04, 0xc9, 0xc6,
	0xa2, 0x3c, 0x21, 0x69, 0x2e, 0x4e, 0xa8, 0xca, 0xcc, 0x14, 0x09, 0x16, 0xb0, 0x12, 0x0e, 0x88,
	0x80, 0x67, 0x8a, 0x93, 0xc4, 0x89, 0x47, 0x72, 0x8c, 0x17, 0x1e, 0xc9, 0x31, 0x3e, 0x78, 0x24,
	0xc7, 0x38, 0xe1, 0xb1, 0x1c, 0xc3, 0x85, 0xc7, 0x72, 0x0c, 0x37, 0x1e, 0xcb, 0x31, 0x24, 0xb1,
	0x81, 0xfd, 0x64, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x11, 0x09, 0x1b, 0xfb, 0xf7, 0x00, 0x00,
	0x00,
}

func (m *LbTargetGroupAttachment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LbTargetGroupAttachment) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.AvailabilityZone) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintLbTargetGroupAttachment(dAtA, i, uint64(len(m.AvailabilityZone)))
		i += copy(dAtA[i:], m.AvailabilityZone)
	}
	if m.Port != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintLbTargetGroupAttachment(dAtA, i, uint64(m.Port))
	}
	if len(m.TargetGroupArn) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintLbTargetGroupAttachment(dAtA, i, uint64(len(m.TargetGroupArn)))
		i += copy(dAtA[i:], m.TargetGroupArn)
	}
	if len(m.TargetId) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintLbTargetGroupAttachment(dAtA, i, uint64(len(m.TargetId)))
		i += copy(dAtA[i:], m.TargetId)
	}
	return i, nil
}

func encodeVarintLbTargetGroupAttachment(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *LbTargetGroupAttachment) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AvailabilityZone)
	if l > 0 {
		n += 1 + l + sovLbTargetGroupAttachment(uint64(l))
	}
	if m.Port != 0 {
		n += 1 + sovLbTargetGroupAttachment(uint64(m.Port))
	}
	l = len(m.TargetGroupArn)
	if l > 0 {
		n += 1 + l + sovLbTargetGroupAttachment(uint64(l))
	}
	l = len(m.TargetId)
	if l > 0 {
		n += 1 + l + sovLbTargetGroupAttachment(uint64(l))
	}
	return n
}

func sovLbTargetGroupAttachment(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozLbTargetGroupAttachment(x uint64) (n int) {
	return sovLbTargetGroupAttachment(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *LbTargetGroupAttachment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLbTargetGroupAttachment
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LbTargetGroupAttachment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LbTargetGroupAttachment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AvailabilityZone", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbTargetGroupAttachment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLbTargetGroupAttachment
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLbTargetGroupAttachment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AvailabilityZone = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Port", wireType)
			}
			m.Port = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbTargetGroupAttachment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Port |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetGroupArn", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbTargetGroupAttachment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLbTargetGroupAttachment
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLbTargetGroupAttachment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TargetGroupArn = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLbTargetGroupAttachment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLbTargetGroupAttachment
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLbTargetGroupAttachment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TargetId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLbTargetGroupAttachment(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthLbTargetGroupAttachment
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthLbTargetGroupAttachment
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLbTargetGroupAttachment(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLbTargetGroupAttachment
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLbTargetGroupAttachment
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLbTargetGroupAttachment
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLbTargetGroupAttachment
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthLbTargetGroupAttachment
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowLbTargetGroupAttachment
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipLbTargetGroupAttachment(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthLbTargetGroupAttachment
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthLbTargetGroupAttachment = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLbTargetGroupAttachment   = fmt.Errorf("proto: integer overflow")
)
